/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArRouteImport } from './routes/ar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardForecastRouteImport } from './routes/dashboard.forecast'
import { Route as DashboardExposureRouteImport } from './routes/dashboard.exposure'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AlertIdRouteImport } from './routes/alert.$id'
import { Route as DashboardHistoryTripIdRouteImport } from './routes/dashboard.history.$tripId'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastRoute = DashboardForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExposureRoute = DashboardExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertIdRoute = AlertIdRouteImport.update({
  id: '/alert/$id',
  path: '/alert/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryTripIdRoute = DashboardHistoryTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => DashboardHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/summary': typeof SummaryRoute
  '/alert/$id': typeof AlertIdRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/exposure': typeof DashboardExposureRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/history': typeof DashboardHistoryRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/dashboard/history/$tripId': typeof DashboardHistoryTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/summary': typeof SummaryRoute
  '/alert/$id': typeof AlertIdRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/exposure': typeof DashboardExposureRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/history': typeof DashboardHistoryRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/dashboard/history/$tripId': typeof DashboardHistoryTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/summary': typeof SummaryRoute
  '/alert/$id': typeof AlertIdRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/exposure': typeof DashboardExposureRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/history': typeof DashboardHistoryRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/dashboard/history/$tripId': typeof DashboardHistoryTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ar'
    | '/dashboard'
    | '/map'
    | '/profile'
    | '/routes'
    | '/summary'
    | '/alert/$id'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/exposure'
    | '/dashboard/forecast'
    | '/dashboard/history'
    | '/onboarding/$step'
    | '/dashboard/history/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ar'
    | '/dashboard'
    | '/map'
    | '/profile'
    | '/routes'
    | '/summary'
    | '/alert/$id'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/exposure'
    | '/dashboard/forecast'
    | '/dashboard/history'
    | '/onboarding/$step'
    | '/dashboard/history/$tripId'
  id:
    | '__root__'
    | '/'
    | '/ar'
    | '/dashboard'
    | '/map'
    | '/profile'
    | '/routes'
    | '/summary'
    | '/alert/$id'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/exposure'
    | '/dashboard/forecast'
    | '/dashboard/history'
    | '/onboarding/$step'
    | '/dashboard/history/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArRoute: typeof ArRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  RoutesRoute: typeof RoutesRoute
  SummaryRoute: typeof SummaryRoute
  AlertIdRoute: typeof AlertIdRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecast': {
      id: '/dashboard/forecast'
      path: '/forecast'
      fullPath: '/dashboard/forecast'
      preLoaderRoute: typeof DashboardForecastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exposure': {
      id: '/dashboard/exposure'
      path: '/exposure'
      fullPath: '/dashboard/exposure'
      preLoaderRoute: typeof DashboardExposureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/$id': {
      id: '/alert/$id'
      path: '/alert/$id'
      fullPath: '/alert/$id'
      preLoaderRoute: typeof AlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history/$tripId': {
      id: '/dashboard/history/$tripId'
      path: '/$tripId'
      fullPath: '/dashboard/history/$tripId'
      preLoaderRoute: typeof DashboardHistoryTripIdRouteImport
      parentRoute: typeof DashboardHistoryRoute
    }
  }
}

interface DashboardHistoryRouteChildren {
  DashboardHistoryTripIdRoute: typeof DashboardHistoryTripIdRoute
}

const DashboardHistoryRouteChildren: DashboardHistoryRouteChildren = {
  DashboardHistoryTripIdRoute: DashboardHistoryTripIdRoute,
}

const DashboardHistoryRouteWithChildren =
  DashboardHistoryRoute._addFileChildren(DashboardHistoryRouteChildren)

interface DashboardRouteChildren {
  DashboardExposureRoute: typeof DashboardExposureRoute
  DashboardForecastRoute: typeof DashboardForecastRoute
  DashboardHistoryRoute: typeof DashboardHistoryRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardExposureRoute: DashboardExposureRoute,
  DashboardForecastRoute: DashboardForecastRoute,
  DashboardHistoryRoute: DashboardHistoryRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArRoute: ArRoute,
  DashboardRoute: DashboardRouteWithChildren,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  RoutesRoute: RoutesRoute,
  SummaryRoute: SummaryRoute,
  AlertIdRoute: AlertIdRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  OnboardingStepRoute: OnboardingStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
